# Generated by Django 5.2.17 on 2026-09-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.EmailField(blank=True, max_length=255, verbose_name="邮箱"),
        ),
    ]
